name: Build release binaries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install Playwright & Chromium
        run: python -m playwright install chromium

      - name: Install system deps (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 \
            libxrandr2 libasound2t64 libpangocairo-1.0-0 libgtk-3-0 libgbm1

      - name: Build executable
        run: |
          pyinstaller --onefile --collect-data playwright --hidden-import playwright.sync_api run.py --name instascrape

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: instascrape-${{ runner.os }}
          path: dist/instascrape*
          retention-days: 30
